name: Setup env file contents

on:
  workflow_call:
    outputs:
      env_vars:
        description: 'Vars'
        value: ${{ jobs.env-file.outputs.vars }}

jobs:
  env-file:
    name: 'Workflow: Load ENV Vars'
    runs-on: ubuntu-latest

    outputs:
      vars: ${{ steps.env-setup.outputs.VARS }}

    steps:
      - name: Loading repository variables to real env vars
        id: env-setup
        shell: bash
        env:
          VARS: ${{ toJSON(vars) }}
        run: |
          echo "$VARS" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > ./vars.txt
          
          {
            echo 'VARS<<EOF'
            echo -e "$(/bin/cat ./vars.txt)"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          
          rm ./vars.txt
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
